### ISSUE TITLE
Issues of empty representative information in API output, downloading precompiled databases and database compilation

### ISSUE THREAD

**Issue by sumin383** [rajko-horvat/RevigoPythonExample#1]
Hello,
I am writing all issues I encountered here as the 'Contact Us' page is not working.

Issue 1: Empty Representative Information
Upon API execution, representative information for GO terms with eliminated set to TRUE is populated correctly, but for those with eliminated set to FALSE, the information is consistently empty.
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/user/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/user/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

  | Term ID | Name | Frequency | Value | Uniqueness | Dispensability | Eliminated | Representative
-- | -- | -- | -- | -- | -- | -- | -- | --
0 | GO:0000070 | mitotic sister chromatid segregation | 0.07% | -23 | 0.86 | 0.61 | FALSE |  
1 | GO:0000819 | sister chromatid segregation | 0.08% | -23 | 0.86 | 0.91 | TRUE | 70
2 | GO:0007076 | mitotic chromosome condensation | 0.03% | -23 | 0.86 | 0.94 | TRUE | 70
3 | GO:0000087 | mitotic M phase | 18.42% | -22 | 0.97 | 0 | FALSE |  
4 | GO:0000279 | M phase | 18.42% | -22 | 0.97 | 0.82 | TRUE | 87
5 | GO:0022403 | cell cycle phase | 18.42% | -22 | 0.97 | 0.82 | TRUE | 87
6 | GO:0000278 | mitotic cell cycle | 0.34% | -23 | 0.93 | 0.01 | FALSE |  
7 | GO:0022402 | cell cycle process | 0.98% | -22 | 0.93 | 0.77 | TRUE | 278
8 | GO:0002252 | immune effector process | 0.06% | -5 | 0.88 | 0 | FALSE |  

</body>

</html>

I am using the following code to call the API:
```python
import requests
import pandas as pd

# Read enrichments file
input_fn = './RevigoPythonExample/Example1.csv'
userData = open(input_fn,'r').read()

# Submit job to Revigo
payload = {'cutoff':'0.7', 'valueType':'pvalue', 'speciesTaxon':'0', 'measure':'SIMREL', 'goList':userData, 'removeObsolete':'true'}
r = requests.post("http://revigo.irb.hr/Revigo", data=payload)

result_dfs = pd.read_html(r.text)
result_BP = result_dfs[0].copy()
print(result_BP)
result_BP.to_csv('./RevigoPythonExample/result_html_table.csv')
```
 
Issue 2: Downloading Precompiled Databases
The link provided in the README https://github.com/rajko-horvat/RevigoPythonExample?tab=readme-ov-file for "Download a set of precompiled databases: Gene Ontology (http://revigo.irb.hr/Databases/GeneOntology.xml.gz) and Species annotations (http://revigo.irb.hr/Databases/SpeciesAnnotations.xml.gz)" is not functioning correctly. I kindly request the files "GeneOntology.xml.gz" and "SpeciesAnnotations.xml.gz”.
 
Issue 3: Database Compilation
Despite following the instructions at https://github.com/rajko-horvat/RevigoGenerateDatabases to compile the databases manually, the required files are not generated. After compilation, are 'GeneOntology.xml.gz' and 'SpeciesAnnotations.xml.gz' not generated? After successful compilation, the files generated are as follows in [bin\Release\net6.0\win-x64]:
RevigoCore.dll, RevigoCore.pdb, RevigoGenerateDatabases.deps.json, RevigoGenerateDatabases.dll, RevigoGenerateDatabases.dll.config, RevigoGenerateDatabases.exe, RevigoGenerateDatabases.pdb, RevigoGenerateDatabases.runtimeconfig.json

Environment Information: Python 3.11, Windows 10

If there is additional information you require or a specific process for reporting such issues, please let me know.
Thank you for your time and support.

**Comment by rajko-horvat** [comment]
> Hello, I am writing all issues I encountered here as the 'Contact Us' page is not working.
> 
Contact page should work now. I don't know why Google captcha didn't want to work

> Issue 1: Empty Representative Information Upon API execution, representative information for GO terms with eliminated set to TRUE is populated correctly, but for those with eliminated set to FALSE, the information is consistently empty.
> 
The following link on our FAQ should answer this question completely:
http://revigo.irb.hr/FAQ#q06

> 
> Issue 2: Downloading Precompiled Databases The link provided in the README https://github.com/rajko-horvat/RevigoPythonExample?tab=readme-ov-file for "Download a set of precompiled databases: Gene Ontology (http://revigo.irb.hr/Databases/GeneOntology.xml.gz) and Species annotations (http://revigo.irb.hr/Databases/SpeciesAnnotations.xml.gz)" is not functioning correctly. I kindly request the files "GeneOntology.xml.gz" and "SpeciesAnnotations.xml.gz”.
> 
Your Web browser is making the fuss about downloading files from http, I guess it's Chrome. Just open new tab and paste the link to a database file that you require. Web browser should complain and offer you to keep the file, click keep and the file should be downloaded.

> Issue 3: Database Compilation Despite following the instructions at https://github.com/rajko-horvat/RevigoGenerateDatabases to compile the databases manually, the required files are not generated. After compilation, are 'GeneOntology.xml.gz' and 'SpeciesAnnotations.xml.gz' not generated?

No, you should run the generated executable to generate databases.

> After successful compilation, the files generated are as follows in [bin\Release\net6.0\win-x64]: RevigoCore.dll, RevigoCore.pdb, RevigoGenerateDatabases.deps.json, RevigoGenerateDatabases.dll, RevigoGenerateDatabases.dll.config, RevigoGenerateDatabases.exe, RevigoGenerateDatabases.pdb, RevigoGenerateDatabases.runtimeconfig.json
> 
> Environment Information: Python 3.11, Windows 10
> 
The [RevigoGenerateDatabases ](https://github.com/rajko-horvat/RevigoGenerateDatabases) Readme should be followed exactly!
First download and unpack all prerequisite databases mentioned in Readme, and then you should adjust the paths to databases in Program.cs, then you should compile the RevigoGenerateDatabases project and finally run the generated program. 
If paths to databases are properly adjusted, and databases unpacked (the program will tell you) the process should take about few hours.

> If there is additional information you require or a specific process for reporting such issues, please let me know. Thank you for your time and support.

**Comment by rajko-horvat** [comment]
Please let me know if you succeeded.

**Comment by sumin383** [comment]
Thank you for your quick response. I still have a few more questions.

Issue 1
After running a Python example using precompiled databases, I realized that I was comparing the BPTable from the API with the BPTreeMap from the web. I apologize for any confusion. Is there a method to obtain the BPTreeMap from the API?

Issue 2
Following your guidance, I successfully downloaded it! Thank you.

Issue 3
After adjusting the paths to databases in Program.cs, I compiled the RevigoGenerateDatabases project. However, nothing was generated under the adjusted path after running RevigoGenerateDatabases.exe. I expected 'GeneOntology.xml.gz' and 'SpeciesAnnotations.xml.gz' to be generated in the path I adjusted after running the exe. Is it correct?

**Comment by rajko-horvat** [comment]
> Thank you for your quick response. I still have a few more questions.
> 
> Issue 1 After running a Python example using precompiled databases, I realized that I was comparing the BPTable from the API with the BPTreeMap from the web. I apologize for any confusion. Is there a method to obtain the BPTreeMap from the API?

Yes, use The advanced job submitting method. Example in Python is available on our FAQ page.

> 
> Issue 2 Following your guidance, I successfully downloaded it! Thank you.
> 
> Issue 3 After adjusting the paths to databases in Program.cs, I compiled the RevigoGenerateDatabases project. However, nothing was generated under the adjusted path after running RevigoGenerateDatabases.exe. I expected 'GeneOntology.xml.gz' and 'SpeciesAnnotations.xml.gz' to be generated in the path I adjusted after running the exe. Is it correct?

Did you receive any errors? Please run this utility from command prompt to see program output (including any possible errors). If program finished instantly there was definitely an error. In program.cs there are two paths that define where ontology and annotations will be stored (serialized).

**Comment by rajko-horvat** [comment]
Ok, I'm going to close this, as this is just support and not a real bug.
